### ISSUE TITLE
Hugo site will not render with connectome theme installed

### ISSUE THREAD

**Issue by GrantsTracks2121** [kausalflow/connectome#11]
Hi there,

I'm very interested in checking out this theme but I'm unable to render any pages. Four instances of the same error stop the build process:

failed to render pages: render of "page" failed: "/Volumes/Resources_Storage/Hugo Sandbox/connectome/layouts/_default/baseof.html:5:10": execute of template failed: template: project/single.html:5:10: executing "project/single.html" at <.Hugo.Generator>: can't evaluate field Hugo in type *hugolib.pageState

I've looked at /project/single.html but I'm not savvy enough to figure out what is wrong.

Using Hugo version: v0.105.0+extended

Thanks in advance for any help you might be able to give me.

**Comment by GrantsTracks2121** [comment]
Hi there - I found the online example site after submitting this issue. I admire the work you've put into this, but I've decided the  format isn't for me.

**Comment by emptymalei** [comment]
You may like this theme instead

https://github.com/jackyzha0/quartz

**Comment by GrantsTracks2121** [comment]
Thanks very much for taking the time to point out an alternative. As it happens I do have Quartz installed and really like it. But that wasn't stopping me from looking for other alternatives. 😉

Thanks again and take care.

**Comment by emptymalei** [comment]
Thanks and good luck with the explorations. 😸
