### ISSUE TITLE
removeOpenClass() is not defined in partials/network/graph.html

### ISSUE THREAD

**Issue by Andersang** [kausalflow/connectome#2]
Under [partials/network/graph.html](https://github.com/kausalflow/connectome/blob/master/layouts/partials/network/graph.html) as well as [partials/network/graph_modal.html](https://github.com/kausalflow/connectome/blob/master/layouts/partials/network/graph-modal.html), the function removeOpenClass() is not defined, thus clicking on nodes in the graph does not do anything.

**Comment by emptymalei** [comment]
Hi @Andersang thanks for reporting this bug. 

I think we can safely remove this function here.

**Comment by emptymalei** [comment]
Closing as we moved away from this jquery library.
