### ISSUE TITLE
White space generated by Hugo local server with list.network.json

### ISSUE THREAD

**Issue by Andersang** [kausalflow/connectome#3]
When running Hugo in a local server, white space is created in [list.network.json](https://github.com/kausalflow/connectome/blob/master/layouts/_default/list.network.json) generates a lot of white space. [See image for reference.](https://snipboard.io/5D9UWC.jpg). 

Hugo v0.89.1, running `hugo server -e production`.

**Comment by emptymalei** [comment]
Hi @Andersang 

Yep. One way to remove these white spaces is to minify the https://github.com/kausalflow/connectome/blob/master/layouts/_default/list.network.json

But that will make it extremely hard to read and debug. I kept it like this.

Would adapt the code if you have a solution to this problem. 😄

**Comment by emptymalei** [comment]
Closing as #5 has been merged.
